repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
      exclude: notebooks
      exclude_types: [svg]
  -   id: trailing-whitespace
      exclude: notebooks
      exclude_types: [svg]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  -   id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
  -   id: ruff
      args: ["--fix", "--output-format=full"]
