#!/bin/sh
# minimize step is too memory intensive and causes the binder
# repo2docker build to crash with MemoryError.
jupyter lab build --dev-build=False  --minimize=False


echo 'export OMP_NUM_THREADS=2' >> ~/.profile
echo 'export OPENBLAS_NUM_THREADS=2' >> ~/.profile
echo 'export MKL_NUM_THREADS=2' >> ~/.profile
