#######################################################################################
# Book settings
title : Scikit-learn tutorial
author: scikit-learn developers
logo: 'scikit-learn-logo.png'

# Information about where the book exists on the web
description: >-
  scikit-learn tutorial
exclude_patterns:
  -  _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - "figures"
  - "datasets"
  - "README.md"


#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  timeout                     : 300

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issues_button           : true
  favicon: _static/favicon.ico
  comments:
    hypothesis: true

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/INRIA/scikit-learn-mooc

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
