#######################################################################################
# Book settings
title : Scikit-learn tutorial
author: scikit-learn developers
logo: 'scikit-learn-logo.png'

# Information about where the book exists on the web
description: >-
  scikit-learn tutorial

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  timeout                     : 300

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/INRIA/scikit-learn-mooc
  path_to_book                : "python_scripts"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
