name: deploy-gh-pages

on:
  push:
    branches:
    - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 2
      MKL_NUM_THREADS: 2
      OPENBLAS_NUM_THREADS: 2

    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jupyter-book

    - name: Build the book
      run: |
        cd jupyter-book
        make

    - name: Create folder for gh-pages 
      run: |
        cp -r jupyter-book/_build/html gh-pages

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
