name: slides-ci

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install python dependencies
      working-directory: ./slides
      run: pip install -r requirements.txt

    - name: Export html
      working-directory: ./slides
      run: make && mkdir ../dist && mv *.html ../dist/

    - name: Upload distributed files
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
